=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigiKey::MediaResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MediaResponse' do
  before do
    # run before each test
    @instance = DigiKey::MediaResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MediaResponse' do
    it 'should create an instance of MediaResponse' do
      expect(@instance).to be_instance_of(DigiKey::MediaResponse)
    end
  end
  describe 'test attribute "media_links"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
