=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigiKey::ParameterValue
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ParameterValue' do
  before do
    # run before each test
    @instance = DigiKey::ParameterValue.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ParameterValue' do
    it 'should create an instance of ParameterValue' do
      expect(@instance).to be_instance_of(DigiKey::ParameterValue)
    end
  end
  describe 'test attribute "parameter_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "parameter_text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "parameter_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["String", "Integer", "Double", "UnitOfMeasure", "CoupledUnitOfMeasure", "RangeUnitOfMeasure"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.parameter_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "value_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value_text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
