=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigiKey::SortOptions
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SortOptions' do
  before do
    # run before each test
    @instance = DigiKey::SortOptions.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SortOptions' do
    it 'should create an instance of SortOptions' do
      expect(@instance).to be_instance_of(DigiKey::SortOptions)
    end
  end
  describe 'test attribute "field"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["None", "Packaging", "ProductStatus", "DigiKeyProductNumber", "ManufacturerProductNumber", "Manufacturer", "MinimumQuantity", "QuantityAvailable", "Price", "Supplier", "PriceManufacturerStandardPackage"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.field = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "sort_order"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Ascending", "Descending"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.sort_order = value }.not_to raise_error
      # end
    end
  end

end
