=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module DigiKey
  # Filtering options for keyword search
  class FilterOptionsRequest
    # Filter on Manufacturer
    attr_accessor :manufacturer_filter

    # Category
    attr_accessor :category_filter

    # Status
    attr_accessor :status_filter

    # Packaging
    attr_accessor :packaging_filter

    # MarketPlaceFilter
    attr_accessor :market_place_filter

    # SeriesFilter
    attr_accessor :series_filter

    # The MinimumQuantityAvailable for the result to display
    attr_accessor :minimum_quantity_available

    attr_accessor :parameter_filter_request

    # /SearchOptions
    attr_accessor :search_options

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'manufacturer_filter' => :'ManufacturerFilter',
        :'category_filter' => :'CategoryFilter',
        :'status_filter' => :'StatusFilter',
        :'packaging_filter' => :'PackagingFilter',
        :'market_place_filter' => :'MarketPlaceFilter',
        :'series_filter' => :'SeriesFilter',
        :'minimum_quantity_available' => :'MinimumQuantityAvailable',
        :'parameter_filter_request' => :'ParameterFilterRequest',
        :'search_options' => :'SearchOptions'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'manufacturer_filter' => :'Array<FilterId>',
        :'category_filter' => :'Array<FilterId>',
        :'status_filter' => :'Array<FilterId>',
        :'packaging_filter' => :'Array<FilterId>',
        :'market_place_filter' => :'String',
        :'series_filter' => :'Array<FilterId>',
        :'minimum_quantity_available' => :'Integer',
        :'parameter_filter_request' => :'ParameterFilterRequest',
        :'search_options' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'ManufacturerFilter')
        if (value = attributes[:'ManufacturerFilter']).is_a?(Array)
          self.manufacturer_filter = value
        end
      end

      if attributes.has_key?(:'CategoryFilter')
        if (value = attributes[:'CategoryFilter']).is_a?(Array)
          self.category_filter = value
        end
      end

      if attributes.has_key?(:'StatusFilter')
        if (value = attributes[:'StatusFilter']).is_a?(Array)
          self.status_filter = value
        end
      end

      if attributes.has_key?(:'PackagingFilter')
        if (value = attributes[:'PackagingFilter']).is_a?(Array)
          self.packaging_filter = value
        end
      end

      if attributes.has_key?(:'MarketPlaceFilter')
        self.market_place_filter = attributes[:'MarketPlaceFilter']
      end

      if attributes.has_key?(:'SeriesFilter')
        if (value = attributes[:'SeriesFilter']).is_a?(Array)
          self.series_filter = value
        end
      end

      if attributes.has_key?(:'MinimumQuantityAvailable')
        self.minimum_quantity_available = attributes[:'MinimumQuantityAvailable']
      end

      if attributes.has_key?(:'ParameterFilterRequest')
        self.parameter_filter_request = attributes[:'ParameterFilterRequest']
      end

      if attributes.has_key?(:'SearchOptions')
        if (value = attributes[:'SearchOptions']).is_a?(Array)
          self.search_options = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      market_place_filter_validator = EnumAttributeValidator.new('String', ['NoFilter', 'ExcludeMarketPlace', 'MarketPlaceOnly'])
      return false unless market_place_filter_validator.valid?(@market_place_filter)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] market_place_filter Object to be assigned
    def market_place_filter=(market_place_filter)
      validator = EnumAttributeValidator.new('String', ['NoFilter', 'ExcludeMarketPlace', 'MarketPlaceOnly'])
      unless validator.valid?(market_place_filter)
        fail ArgumentError, 'invalid value for "market_place_filter", must be one of #{validator.allowable_values}.'
      end
      @market_place_filter = market_place_filter
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          manufacturer_filter == o.manufacturer_filter &&
          category_filter == o.category_filter &&
          status_filter == o.status_filter &&
          packaging_filter == o.packaging_filter &&
          market_place_filter == o.market_place_filter &&
          series_filter == o.series_filter &&
          minimum_quantity_available == o.minimum_quantity_available &&
          parameter_filter_request == o.parameter_filter_request &&
          search_options == o.search_options
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [manufacturer_filter, category_filter, status_filter, packaging_filter, market_place_filter, series_filter, minimum_quantity_available, parameter_filter_request, search_options].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DigiKey.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
