=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module DigiKey
  class FilterOptions
    # The Manufacturers that can be filtered to narrow next search request
    attr_accessor :manufacturers

    # Packaging that can be filtered to narrow next search request
    attr_accessor :packaging

    # Status that can be filtered to narrow next search request
    attr_accessor :status

    # Series that can be filtered to narrow next search request
    attr_accessor :series

    # ParaetricFilter that can be filtered to narrow next search request
    attr_accessor :parametric_filters

    # the top Categories to filter
    attr_accessor :top_categories

    # Marketplace Filter
    attr_accessor :market_place_filters

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'manufacturers' => :'Manufacturers',
        :'packaging' => :'Packaging',
        :'status' => :'Status',
        :'series' => :'Series',
        :'parametric_filters' => :'ParametricFilters',
        :'top_categories' => :'TopCategories',
        :'market_place_filters' => :'MarketPlaceFilters'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'manufacturers' => :'Array<BaseFilterV4>',
        :'packaging' => :'Array<BaseFilterV4>',
        :'status' => :'Array<BaseFilterV4>',
        :'series' => :'Array<BaseFilterV4>',
        :'parametric_filters' => :'Array<ParameterFilterOptionsResponse>',
        :'top_categories' => :'Array<TopCategory>',
        :'market_place_filters' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'Manufacturers')
        if (value = attributes[:'Manufacturers']).is_a?(Array)
          self.manufacturers = value
        end
      end

      if attributes.has_key?(:'Packaging')
        if (value = attributes[:'Packaging']).is_a?(Array)
          self.packaging = value
        end
      end

      if attributes.has_key?(:'Status')
        if (value = attributes[:'Status']).is_a?(Array)
          self.status = value
        end
      end

      if attributes.has_key?(:'Series')
        if (value = attributes[:'Series']).is_a?(Array)
          self.series = value
        end
      end

      if attributes.has_key?(:'ParametricFilters')
        if (value = attributes[:'ParametricFilters']).is_a?(Array)
          self.parametric_filters = value
        end
      end

      if attributes.has_key?(:'TopCategories')
        if (value = attributes[:'TopCategories']).is_a?(Array)
          self.top_categories = value
        end
      end

      if attributes.has_key?(:'MarketPlaceFilters')
        if (value = attributes[:'MarketPlaceFilters']).is_a?(Array)
          self.market_place_filters = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          manufacturers == o.manufacturers &&
          packaging == o.packaging &&
          status == o.status &&
          series == o.series &&
          parametric_filters == o.parametric_filters &&
          top_categories == o.top_categories &&
          market_place_filters == o.market_place_filters
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [manufacturers, packaging, status, series, parametric_filters, top_categories, market_place_filters].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DigiKey.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
