=begin
#ProductSearch Api

#ProductSearch Api

OpenAPI spec version: v4
Contact: dl_Agile_Team_B2B_API@digikey.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.43

=end

require 'date'

module DigiKey
  # Aggregator Product Dto
  class PackageTypeByQuantityProduct
    # Recommended quantity for product
    attr_accessor :recommended_quantity

    # The Digi-Key part number.
    attr_accessor :digi_key_product_number

    # Quantity of the product available for immediate sale.
    attr_accessor :quantity_available

    # Catalog description of the product.
    attr_accessor :product_description

    # Extended catalog description of the product.
    attr_accessor :detailed_description

    # Manufacturer of the product.
    attr_accessor :manufacturer_name

    # The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for  different parts.
    attr_accessor :manufacturer_product_number

    # The minimum quantity to order from Digi-Key.
    attr_accessor :minimum_order_quantity

    # The URL to the product's datasheet.
    attr_accessor :primary_datasheet_url

    # The URL to the product's image.
    attr_accessor :primary_photo_url

    # Status of the product. Options include: Active, Obsolete, Discontinued at Digi-Key,  Last Time Buy, Not For New Designs, Preliminary. For obsolete parts the part  will become a non-stocking item when stock is depleted; minimums will apply.  Order the quantity available or the quantity available plus a multiple of the  minimum order quantity.  ///
    attr_accessor :product_status

    # The number of weeks expected to receive stock from manufacturer.
    attr_accessor :manufacturer_lead_weeks

    # Quantity of this product available to order from manufacturer.
    attr_accessor :manufacturer_warehouse_quantity

    # RoHS status. Can be RoHS Compliant, RoHS non-compliant, RoHS Compliant By Exemption, Not Applicable, Vendor  undefined, Request Inventory Verification, or ROHS3 Compliant.
    attr_accessor :rohs_status

    # Boolean value for RoHS compliance.
    attr_accessor :ro_hs_compliant

    # Quantity of this product ordered but not immediately available.
    attr_accessor :quantity_on_order

    # Standard pricing for the validated locale.
    attr_accessor :standard_pricing

    # My pricing for the validated locale.
    attr_accessor :my_pricing

    # Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.
    attr_accessor :product_url

    # Is this product a marketplace product
    attr_accessor :market_place

    # Name of product supplier
    attr_accessor :supplier

    # Description of Digi-Key's current stocking status for the product. Possible values include: In Stock, Temporarily  Out of Stock, and Limited Supply - Call.
    attr_accessor :stock_note

    attr_accessor :package_types

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'recommended_quantity' => :'RecommendedQuantity',
        :'digi_key_product_number' => :'DigiKeyProductNumber',
        :'quantity_available' => :'QuantityAvailable',
        :'product_description' => :'ProductDescription',
        :'detailed_description' => :'DetailedDescription',
        :'manufacturer_name' => :'ManufacturerName',
        :'manufacturer_product_number' => :'ManufacturerProductNumber',
        :'minimum_order_quantity' => :'MinimumOrderQuantity',
        :'primary_datasheet_url' => :'PrimaryDatasheetUrl',
        :'primary_photo_url' => :'PrimaryPhotoUrl',
        :'product_status' => :'ProductStatus',
        :'manufacturer_lead_weeks' => :'ManufacturerLeadWeeks',
        :'manufacturer_warehouse_quantity' => :'ManufacturerWarehouseQuantity',
        :'rohs_status' => :'RohsStatus',
        :'ro_hs_compliant' => :'RoHSCompliant',
        :'quantity_on_order' => :'QuantityOnOrder',
        :'standard_pricing' => :'StandardPricing',
        :'my_pricing' => :'MyPricing',
        :'product_url' => :'ProductUrl',
        :'market_place' => :'MarketPlace',
        :'supplier' => :'Supplier',
        :'stock_note' => :'StockNote',
        :'package_types' => :'PackageTypes'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'recommended_quantity' => :'Integer',
        :'digi_key_product_number' => :'String',
        :'quantity_available' => :'Integer',
        :'product_description' => :'String',
        :'detailed_description' => :'String',
        :'manufacturer_name' => :'String',
        :'manufacturer_product_number' => :'String',
        :'minimum_order_quantity' => :'Integer',
        :'primary_datasheet_url' => :'String',
        :'primary_photo_url' => :'String',
        :'product_status' => :'String',
        :'manufacturer_lead_weeks' => :'String',
        :'manufacturer_warehouse_quantity' => :'Integer',
        :'rohs_status' => :'String',
        :'ro_hs_compliant' => :'BOOLEAN',
        :'quantity_on_order' => :'Integer',
        :'standard_pricing' => :'Array<PriceBreak>',
        :'my_pricing' => :'Array<PriceBreak>',
        :'product_url' => :'String',
        :'market_place' => :'BOOLEAN',
        :'supplier' => :'String',
        :'stock_note' => :'String',
        :'package_types' => :'Array<String>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'RecommendedQuantity')
        self.recommended_quantity = attributes[:'RecommendedQuantity']
      end

      if attributes.has_key?(:'DigiKeyProductNumber')
        self.digi_key_product_number = attributes[:'DigiKeyProductNumber']
      end

      if attributes.has_key?(:'QuantityAvailable')
        self.quantity_available = attributes[:'QuantityAvailable']
      end

      if attributes.has_key?(:'ProductDescription')
        self.product_description = attributes[:'ProductDescription']
      end

      if attributes.has_key?(:'DetailedDescription')
        self.detailed_description = attributes[:'DetailedDescription']
      end

      if attributes.has_key?(:'ManufacturerName')
        self.manufacturer_name = attributes[:'ManufacturerName']
      end

      if attributes.has_key?(:'ManufacturerProductNumber')
        self.manufacturer_product_number = attributes[:'ManufacturerProductNumber']
      end

      if attributes.has_key?(:'MinimumOrderQuantity')
        self.minimum_order_quantity = attributes[:'MinimumOrderQuantity']
      end

      if attributes.has_key?(:'PrimaryDatasheetUrl')
        self.primary_datasheet_url = attributes[:'PrimaryDatasheetUrl']
      end

      if attributes.has_key?(:'PrimaryPhotoUrl')
        self.primary_photo_url = attributes[:'PrimaryPhotoUrl']
      end

      if attributes.has_key?(:'ProductStatus')
        self.product_status = attributes[:'ProductStatus']
      end

      if attributes.has_key?(:'ManufacturerLeadWeeks')
        self.manufacturer_lead_weeks = attributes[:'ManufacturerLeadWeeks']
      end

      if attributes.has_key?(:'ManufacturerWarehouseQuantity')
        self.manufacturer_warehouse_quantity = attributes[:'ManufacturerWarehouseQuantity']
      end

      if attributes.has_key?(:'RohsStatus')
        self.rohs_status = attributes[:'RohsStatus']
      end

      if attributes.has_key?(:'RoHSCompliant')
        self.ro_hs_compliant = attributes[:'RoHSCompliant']
      end

      if attributes.has_key?(:'QuantityOnOrder')
        self.quantity_on_order = attributes[:'QuantityOnOrder']
      end

      if attributes.has_key?(:'StandardPricing')
        if (value = attributes[:'StandardPricing']).is_a?(Array)
          self.standard_pricing = value
        end
      end

      if attributes.has_key?(:'MyPricing')
        if (value = attributes[:'MyPricing']).is_a?(Array)
          self.my_pricing = value
        end
      end

      if attributes.has_key?(:'ProductUrl')
        self.product_url = attributes[:'ProductUrl']
      end

      if attributes.has_key?(:'MarketPlace')
        self.market_place = attributes[:'MarketPlace']
      end

      if attributes.has_key?(:'Supplier')
        self.supplier = attributes[:'Supplier']
      end

      if attributes.has_key?(:'StockNote')
        self.stock_note = attributes[:'StockNote']
      end

      if attributes.has_key?(:'PackageTypes')
        if (value = attributes[:'PackageTypes']).is_a?(Array)
          self.package_types = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          recommended_quantity == o.recommended_quantity &&
          digi_key_product_number == o.digi_key_product_number &&
          quantity_available == o.quantity_available &&
          product_description == o.product_description &&
          detailed_description == o.detailed_description &&
          manufacturer_name == o.manufacturer_name &&
          manufacturer_product_number == o.manufacturer_product_number &&
          minimum_order_quantity == o.minimum_order_quantity &&
          primary_datasheet_url == o.primary_datasheet_url &&
          primary_photo_url == o.primary_photo_url &&
          product_status == o.product_status &&
          manufacturer_lead_weeks == o.manufacturer_lead_weeks &&
          manufacturer_warehouse_quantity == o.manufacturer_warehouse_quantity &&
          rohs_status == o.rohs_status &&
          ro_hs_compliant == o.ro_hs_compliant &&
          quantity_on_order == o.quantity_on_order &&
          standard_pricing == o.standard_pricing &&
          my_pricing == o.my_pricing &&
          product_url == o.product_url &&
          market_place == o.market_place &&
          supplier == o.supplier &&
          stock_note == o.stock_note &&
          package_types == o.package_types
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [recommended_quantity, digi_key_product_number, quantity_available, product_description, detailed_description, manufacturer_name, manufacturer_product_number, minimum_order_quantity, primary_datasheet_url, primary_photo_url, product_status, manufacturer_lead_weeks, manufacturer_warehouse_quantity, rohs_status, ro_hs_compliant, quantity_on_order, standard_pricing, my_pricing, product_url, market_place, supplier, stock_note, package_types].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DigiKey.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
